#!/usr/bin/env python3
"""Generate lightweight SVG assets for the Pokemon JEPA blog post.

The diagrams are intentionally dependency-free so they can be regenerated in
the repo without a plotting stack. Result plots are generated by
run_pokemon_jepa_v3_study.py.
"""

from __future__ import annotations

import argparse
from html import escape
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FIGURE_DIR = ROOT / "figures"
BLOG_PUBLIC: Path | None = None

INK = "#1f2933"
MUTED = "#5f6b7a"
LINE = "#cbd5e1"
BLUE = "#1f6feb"
BLUE_SOFT = "#eaf2ff"
GREEN = "#1f7a4d"
GREEN_SOFT = "#e8f6ef"
RED = "#b42318"
RED_SOFT = "#fff1f0"
GOLD = "#946200"
GOLD_SOFT = "#fff8df"
PANEL = "#f8fafc"


def write_svg(name: str, svg: str) -> None:
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    roots = [FIGURE_DIR]
    if BLOG_PUBLIC is not None:
        BLOG_PUBLIC.mkdir(parents=True, exist_ok=True)
        roots.append(BLOG_PUBLIC)
    for root in roots:
        (root / name).write_text(svg, encoding="utf-8")


def text(x: float, y: float, value: str, *, size: int = 14, weight: str = "400",
         fill: str = INK, anchor: str = "middle", family: str = "Inter, Arial, sans-serif") -> str:
    return (
        f'<text x="{x}" y="{y}" text-anchor="{anchor}" '
        f'font-family="{family}" font-size="{size}" font-weight="{weight}" '
        f'fill="{fill}">{escape(value)}</text>'
    )


def multiline(x: float, y: float, lines: list[str], *, size: int = 13,
              weight: str = "400", fill: str = MUTED, anchor: str = "middle",
              line_height: int = 18) -> str:
    return "\n".join(
        text(x, y + i * line_height, line, size=size, weight=weight, fill=fill, anchor=anchor)
        for i, line in enumerate(lines)
    )


def box(x: float, y: float, w: float, h: float, *, fill: str, stroke: str,
        radius: int = 10, sw: int = 2) -> str:
    return (
        f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{radius}" '
        f'fill="{fill}" stroke="{stroke}" stroke-width="{sw}" />'
    )


def arrow(x1: float, y1: float, x2: float, y2: float, *, stroke: str = "#64748b") -> str:
    return (
        f'<path d="M {x1} {y1} L {x2} {y2}" stroke="{stroke}" '
        'stroke-width="2.5" fill="none" marker-end="url(#arrowhead)" />'
    )


def hp_bar(x: float, y: float, w: float, hp: int, *, color: str = BLUE) -> str:
    fill_w = max(0, min(w, w * hp / 100))
    return (
        f'<rect x="{x}" y="{y}" width="{w}" height="7" rx="3.5" fill="#e2e8f0" />'
        f'<rect x="{x}" y="{y}" width="{fill_w}" height="7" rx="3.5" fill="{color}" />'
    )


def token_card(x: float, y: float, w: float, h: float, slot: str, name: str, hp: int,
               note: str = "", *, active: bool = False, fainted: bool = False) -> str:
    stroke = BLUE if active else LINE
    fill = "#ffffff" if not fainted else "#f1f5f9"
    name_lines = name.split(" ")
    out = [
        box(x, y, w, h, fill=fill, stroke=stroke, radius=8, sw=2 if active else 1),
        text(x + 12, y + 21, slot, size=11, weight="800", fill=BLUE if active else MUTED, anchor="start"),
    ]
    for i, line in enumerate(name_lines[:2]):
        out.append(text(x + w / 2, y + 48 + i * 15, line, size=13, weight="800", fill=INK))
    out.append(text(x + w / 2, y + 86, f"HP {hp}%", size=12, weight="800", fill=BLUE))
    out.append(hp_bar(x + 14, y + 96, w - 28, hp, color=RED if hp <= 25 else BLUE))
    if note:
        out.append(text(x + w / 2, y + h - 15, note, size=10, fill=MUTED))
    return "\n".join(out)


def defs() -> str:
    return """<defs>
  <marker id="arrowhead" markerWidth="10" markerHeight="8" refX="9" refY="4" orient="auto">
    <polygon points="0 0, 10 4, 0 8" fill="#64748b" />
  </marker>
</defs>"""


def generate_arch_svg() -> None:
    svg = f"""<svg viewBox="0 0 960 540" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="title desc">
  <title id="title">Pokemon JEPA architecture</title>
  <desc id="desc">A 12-token Pokemon battle state flows through a Transformer encoder into a latent state with next-HP, winner, and masked-species heads.</desc>
  <rect width="960" height="540" fill="#ffffff" />
  {defs()}

  {box(40, 165, 190, 190, fill=BLUE_SOFT, stroke=BLUE)}
  {text(135, 200, "Input State", size=17, weight="800")}
  {multiline(135, 230, ["12 Pokemon object tokens", "species id + HP + status", "optional item/move ids"], size=13)}
  {box(75, 294, 120, 38, fill="#ffffff", stroke="#9bbcf7", radius=8, sw=1)}
  {text(135, 318, "x_t", size=18, weight="800", fill=BLUE)}

  {arrow(230, 260, 285, 260)}

  {box(285, 130, 235, 260, fill="#fff7ed", stroke="#f97316")}
  {text(402.5, 166, "Transformer Encoder", size=17, weight="800")}
  {multiline(402.5, 200, ["self-attention over slots", "active threats see bench answers", "2 layers / 4 heads in study", "3 layers / 8 heads in teambuilder"], size=13)}
  {box(330, 315, 145, 42, fill="#ffffff", stroke="#fdba74", radius=8, sw=1)}
  {text(402.5, 341, "object interactions", size=13, weight="800", fill="#9a3412")}

  {arrow(520, 260, 585, 260)}

  {box(585, 215, 130, 90, fill=BLUE, stroke="#0b3b8f", radius=20)}
  {text(650, 253, "Latent z", size=18, weight="800", fill="#ffffff")}
  {text(650, 278, "128-256 dims", size=12, weight="700", fill="#dbeafe")}

  {arrow(715, 242, 780, 132)}
  {arrow(715, 260, 780, 260)}
  {arrow(715, 278, 780, 388)}

  {box(780, 78, 150, 108, fill=GREEN_SOFT, stroke=GREEN)}
  {text(855, 111, "JEPA Head", size=15, weight="800")}
  {multiline(855, 139, ["predict HP(t+1)", "12-slot regression"], size=12, fill="#2f6f4e")}

  {box(780, 206, 150, 108, fill=RED_SOFT, stroke=RED)}
  {text(855, 239, "Winner Head", size=15, weight="800")}
  {multiline(855, 267, ["predict final", "battle outcome"], size=12, fill="#8a241d")}

  {box(780, 334, 150, 108, fill=GOLD_SOFT, stroke=GOLD)}
  {text(855, 367, "Mask Head", size=15, weight="800")}
  {multiline(855, 395, ["fill missing", "team slot"], size=12, fill="#745008")}

  {text(480, 500, "The key pressure: useful latents must explain how the board moves, not only who won.", size=15, weight="700", fill=MUTED)}
</svg>"""
    write_svg("jepa-arch.svg", svg)


def generate_battle_state_schematic() -> None:
    p1 = [
        ("Active", "Salazzle", 100, "special"),
        ("Bench 1", "Bellibolt", 100, "bulky"),
        ("Bench 2", "Cryogonal", 100, ""),
        ("Bench 3", "Grimmsnarl", 100, ""),
        ("Bench 4", "Tauros Aqua", 100, ""),
        ("Bench 5", "Rotom Mow", 100, ""),
    ]
    p2 = [
        ("Active", "Froslass", 100, ""),
        ("Bench 1", "Coalossal", 100, "fire wall"),
        ("Bench 2", "Scream Tail", 100, "special wall"),
        ("Bench 3", "Grimmsnarl", 100, ""),
        ("Bench 4", "Dusknoir", 100, ""),
        ("Bench 5", "Clawitzer", 100, ""),
    ]
    cards = []
    for i, mon in enumerate(p1):
        cards.append(token_card(40 + i * 158, 145, 140, 126, *mon, active=i == 0))
    for i, mon in enumerate(p2):
        cards.append(token_card(40 + i * 158, 330, 140, 126, *mon, active=i == 0))

    svg = f"""<svg viewBox="0 0 1040 600" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="title desc">
  <title id="title">Battle-state schematic</title>
  <desc id="desc">A Pokemon battle state represented as twelve object tokens, six per side, with active Pokemon and bench Pokemon encoded together.</desc>
  <rect width="1040" height="600" fill="#ffffff" />
  {defs()}

  {text(520, 50, "Battle State as 12 Object Tokens", size=25, weight="900")}
  {text(520, 80, "One turn becomes a fixed sequence: active slot plus five bench slots for each player.", size=15, fill=MUTED)}

  {box(40, 108, 930, 34, fill=BLUE_SOFT, stroke="#bfdbfe", radius=8, sw=1)}
  {text(58, 130, "P1 tokens", size=13, weight="900", fill=BLUE, anchor="start")}
  {box(40, 293, 930, 34, fill=RED_SOFT, stroke="#fecaca", radius=8, sw=1)}
  {text(58, 315, "P2 tokens", size=13, weight="900", fill=RED, anchor="start")}

  {"".join(cards)}

  {arrow(500, 470, 500, 515)}
  {box(220, 515, 560, 50, fill=PANEL, stroke=LINE, radius=10, sw=1)}
  {text(500, 538, "Tensor rows: [slot id, side id, species id, normalized HP, status id, item/move ids]", size=14, weight="800")}
  {text(500, 558, "The Transformer sees cross-team interactions, not isolated handcrafted totals.", size=12, fill=MUTED)}
</svg>"""
    write_svg("pokemon-battle-state-schematic.svg", svg)


def generate_learning_target_svg() -> None:
    svg = f"""<svg viewBox="0 0 1040 560" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="title desc">
  <title id="title">Pokemon JEPA learning target</title>
  <desc id="desc">A sample input state and target for next-turn HP prediction and winner prediction.</desc>
  <rect width="1040" height="560" fill="#ffffff" />
  {defs()}

  {text(520, 45, "One Training Example", size=25, weight="900")}
  {text(520, 74, "The model is not given the next move. It sees the current board and learns the next HP vector plus the final winner.", size=14, fill=MUTED)}

  {box(40, 112, 340, 360, fill=BLUE_SOFT, stroke=BLUE)}
  {text(210, 145, "Input x_t", size=18, weight="900")}
  {multiline(210, 174, ["Turn 6 snapshot from a replay", "12 slots, shown here as a compact excerpt"], size=12)}
  {token_card(70, 222, 130, 120, "P1 active", "Delphox", 100, "boosted", active=True)}
  {token_card(220, 222, 130, 120, "P2 active", "Bellibolt", 100, "leftovers", active=True)}
  {token_card(70, 352, 130, 104, "P1 bench", "Florges", 90, "")}
  {token_card(220, 352, 130, 104, "P2 bench", "Appletun", 83, "")}

  {arrow(380, 292, 470, 292)}

  {box(470, 202, 155, 180, fill="#fff7ed", stroke="#f97316")}
  {text(547.5, 238, "Encoder", size=18, weight="900")}
  {multiline(547.5, 270, ["self-attention", "over 12 slots"], size=13)}
  {box(500, 322, 95, 38, fill="#ffffff", stroke="#fdba74", radius=8, sw=1)}
  {text(547.5, 346, "latent z", size=14, weight="800", fill="#9a3412")}

  {arrow(625, 292, 710, 292)}

  {box(710, 112, 290, 360, fill=GREEN_SOFT, stroke=GREEN)}
  {text(855, 145, "Targets", size=18, weight="900")}
  {text(742, 185, "Next-turn HP vector y_hp", size=13, weight="900", fill=GREEN, anchor="start")}
  {box(742, 204, 226, 122, fill="#ffffff", stroke="#a7d7bc", radius=8, sw=1)}
  {multiline(758, 229, ["P1 Delphox: 100 -> 49  (delta -51)", "P1 Florges: 90 -> 90  (delta 0)", "P2 Bellibolt: 100 -> 46  (delta -54)", "P2 Appletun: 83 -> 83  (delta 0)", "... eight more slots"], size=12, fill=INK, anchor="start", line_height=20)}
  {text(742, 370, "Auxiliary winner label", size=13, weight="900", fill=RED, anchor="start")}
  {box(742, 389, 226, 48, fill="#ffffff", stroke="#fca5a5", radius=8, sw=1)}
  {text(855, 419, "winner_p1 = 1", size=17, weight="900", fill=RED)}

  {text(520, 520, "JEPA pressure: a good representation must preserve damage, recovery, switching pressure, and long-horizon outcome.", size=14, weight="700", fill=MUTED)}
</svg>"""
    write_svg("pokemon-learning-target.svg", svg)


def main() -> None:
    global BLOG_PUBLIC, FIGURE_DIR
    parser = argparse.ArgumentParser()
    parser.add_argument("--figure-dir", default=str(FIGURE_DIR))
    parser.add_argument("--public-dir", default="")
    args = parser.parse_args()

    FIGURE_DIR = Path(args.figure_dir)
    BLOG_PUBLIC = Path(args.public_dir) if args.public_dir else None

    generate_arch_svg()
    generate_battle_state_schematic()
    generate_learning_target_svg()
    print("Generated jepa-arch.svg, pokemon-battle-state-schematic.svg, and pokemon-learning-target.svg")


if __name__ == "__main__":
    main()
